import { Home, LayoutDashboard, PlusCircle, Settings } from "lucide-react";

export const featureOptions = {
  ROOM: [
    "1+0",
    "1+1",
    "2+1",
    "2+2",
    "3+1",
    "3+2",
    "4+1",
    "4+2",
    "5+1",
    "5+2",
    "6+",
  ],

  KITCHEN: ["Açık Mutfak", "Kapalı Mutfak", "Amerikan Mutfak"],
  PARKING: ["Açık Otopark", "Kapalı Otopark", "Yok", "Açık ve Kapalı Otopark"],
  HEATING: [
    "Doğalgaz (Kombi)",
    "Merkezi",
    "Yerden Isıtma",
    "Klima",
    "Soba",
    "Yok",
  ],
  FLOOR: [
    "Bodrum",
    "Zemin",
    "Yüksek Giriş",
    "Kot Altı 1",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "20+",
  ],
};

export const menuItems = [
  { name: "Dashboard", href: "/admin", icon: LayoutDashboard },
  { name: "İlanlarım", href: "/admin/ilanlar", icon: Home },
  {
    name: "Yeni İlan Ekle",
    href: "/admin/ilanlar/ilan-olustur",
    icon: PlusCircle,
  },
  { name: "Ayarlar", href: "/admin/ayarlar", icon: Settings },
];
